services:
    api: &api
        build:
            context: .
            dockerfile: ./docker/django/Dockerfile
        command: /start
        restart: always
        image: mitch122/katplan:api-${PLZ}v${VERSION}
        container_name: ${NAME}_api
        expose:
            - "9999"
        volumes:
            - media_volume:/app/mediafiles
            - backup_volume:/app/backups
        env_file:
            - ./.envs/.django
            - ./.envs/.postgres
        depends_on:
            - postgres
        networks:
            - katplan_2432_nw

    postgres:
        build:
            context: .
            dockerfile: ./docker/postgres/Dockerfile
        image: mitch122/katplan:db-${PLZ}v${VERSION}
        container_name: ${NAME}_db
        restart: always
        volumes:
            - postgres_data_volume:/var/lib/postgresql/data
        env_file:
            - ./.envs/.postgres
        networks:
            - katplan_2432_nw

    nginx:
        build:
            context: .
            dockerfile: ./docker/nginx/Dockerfile
        image: mitch122/katplan:nginx-${PLZ}v${VERSION}
        container_name: ${NAME}_nginx
        restart: always
        volumes:
            - media_volume:/app/mediafiles
        environment:
            SERVER_NAME: ${DOMAIN}
            API_URL: http://${NAME}_api
        ports:
            - '8001:80'
        depends_on:
            - api
        networks:
            - katplan_2432_nw

networks:
    katplan_2432_nw:
        external: true

volumes:
    media_volume: 
          name: "${NAME}_media"
    backup_volume: 
          name: "${NAME}_backup"
    postgres_data_volume: 
          name: "${NAME}_postgres"
